### ISSUE TITLE
Wrong git hash being built on PR synchronization

### ISSUE THREAD

**Issue by dragos** [drone-plugins/drone-git#41] opened 2017-03-30 16:39 UTC
After pushing a new commit to a branch, Drone picks up the change but checks out the wrong git hash. Notice in the attached image that the git hash in the header (it's actually the correct one) is different from the output of `git log` in the `build` step.

<img width="1328" alt="screen shot 2017-03-30 at 18 31 42" src="https://cloud.githubusercontent.com/assets/133742/24515322/91a59068-1577-11e7-87d2-c8e13c77c2a5.png">

**Comment by dragos** [comment] 2017-03-30 16:43
If I cancel the build and manually restart it from the UI it usually picks up the right commit, but not always. It might be a caching issue (it seems it needs a few minutes before it picks up the new commit).

**Comment by bradrydzewski** [comment] 2017-03-31 01:44
the reason is that drone uses `FETCH_HEAD` when checking out the pull request. This means it may checkout a different sha each time depending on if the user has synchronized the pull request. So this only impacts pull requests and is not a caching issue.

there is a PR to address this https://github.com/drone-plugins/drone-git/pull/38 but it is failing unit tests and therefore cannot be merged.

this isn't something I'm committed to working on personally, but am happy to accept a pull request that has been tested and is passing unit tests.

**Comment by dragos** [comment] 2017-03-31 08:04
What does it mean to "synchronize the pull request"? would `DRONE_GITHUB_MERGE_REF=false` work around this issue?

**Comment by geekdave** [comment] 2017-10-31 16:19
@bradrydzewski as much as I feel dirty suggesting it, would a `time.Sleep(10)` potentially fix this race condition?

**Closed** 2017-10-31 19:39 UTC
Labels: help wanted

**Comment by pehrsoderman** [comment] 2017-11-20 09:27
This bug seems to be alive and kicking when using latest drone with github. It breaks our drone environment, so some kind of workaround would be nice if it can not be fixed.

**Comment by bradrydzewski** [comment] 2017-11-20 16:19
> After pushing a new commit to a branch, Drone picks up the change but checks out the wrong git hash. Notice in the attached image that the git hash in the header (it's actually the correct one)

@dragos this is because the sha represents the head ref but drone clones the merge ref. If you would like drone to checkout the head ref you can configure this as the default behavior setting the `DRONE_GITHUB_MERGE_REF=false` server environment variable.

> This bug seems to be alive and kicking when using latest drone with github. It breaks our drone environment, so some kind of workaround would be nice if it can not be fixed.

@ pehrsoderman this is how drone has always behaved. There have not been any changes to the latest version of drone that would have broken your environment.

The problem is that GitHub creates the merge commit after the pull request hook is triggered. The merge commit sha is therefore not included in the pull request hook because it does not exist yet.  It can take anywhere from seconds to minutes for GitHub to create the merge commit. If the new merge commit is not ready when drone starts the build, FETCH_HEAD will end up checking out an older commit.

I do not see any workaround for this problem. The clone commands used by Drone are the same clone commands used by Travis [1] and Appveyor [2] which leads me to believe this is the optimal solution, despite being flawed.

This is not something I am planning on changing in the core plugin at this time. Please note that you can always create a custom clone plugin, or use custom clone commands, if you do not like the behavior of the default clone plugin.

[1] https://travis-ci.org/blevesearch/bleve/jobs/285917455#L424
[2] https://ci.appveyor.com/project/tboerger/drone-webhook/build/2#L4
