### ISSUE TITLE
plugins git clone public is unsuccessful in ARM64

### ISSUE THREAD

**Issue by DragonSuper** [drone-plugins/drone-git#85] opened 2019-04-25 02:59 UTC
Hi, I can not commit the issue in https://discourse.drone.io/

drone: 1.0
This command is ok.

```
docker run --rm \
    -e DRONE_REMOTE_URL=http://IP:33000/xiaozheng8187/godev.git \
    -e DRONE_WORKSPACE=/go/src/github.com/xiaozheng8187/godev \
    -e DRONE_BUILD_EVENT=push \
    -e DRONE_COMMIT_SHA=a14c724b8d00eff659d9351ec560b67519dbf226 \
    -e DRONE_COMMIT_REF=refs/heads/master \
    plugins/git:linux-arm64
```
But this command is not ok, git clone hang up 
CI/CD is gogs 0.11

```
kind: pipeline
name: godev
clone:
  disable: true
platform:
  os: linux
  arch: arm64
workspace:
  base: /go
  path: src/gogs.xiaozheng.com/super/godev
steps:
- name: clone
  image: plugins/git:linux-arm64
  commands:
  - git clone http://IP:33000/xiaozheng8187/godev.git
```

docker logs j521jqk7ugfots7utxy05mp2u10s88mx

this log as:
```
+ git clone http://IP:33000/xiaozheng8187/godev.git
Cloning into 'godev'...
```

**Comment by tboerger** [comment] 2019-04-25 05:40
Without a proper formatting and without logs we can't really help.

**Comment by DragonSuper** [comment] 2019-04-25 06:06
@tboerger sorry , the format was a bit messy before.
It's all right now，Thanks

**Comment by tboerger** [comment] 2019-04-25 11:17
Why do you want to change the clone plugin at all? The default clone step is using drone/git which provides a multi architecture manifest.

**Comment by DragonSuper** [comment] 2019-04-28 06:46
@tboerger 
Because defaults don't work properly either.
I think it's a docker network problem in this plugin or drone/git.

Drone is building, it creates a docker container.
I enter the container and run ` curl IP:33000 ` (IP:33000 is gogs index)

log as:
docker exec -it 95rmaeqzawn8x0c80zk51nbd5ru69qfv sh
curl IP:33000
curl is timeout

but , I enter other k8s or docker container, curl is not  timeout
look as:
kubectl exec -it myweb-3570405459-l116f bash
curl IP:33000
```
<!DOCTYPE html>
<html>
<head data-suburl="">
...
</html>
```

docker run -it --rm arm64v8/tomcat:8.5-jre11 bash
curl IP:33000
```
<!DOCTYPE html>
<html>
<head data-suburl="">
...
</html>
```

**Comment by bradrydzewski** [comment] 2019-04-28 07:37
I am closing this as unable to reproduce. I am confident this is a network related issue in the host environment, and is not a problem with the plugin. The plugin is working fine at cloud.drone.io on amd64, arm and arm64 machines, and other community members have confirmed this plugin is working in their environments.

**Closed as completed by bradrydzewski** 2019-04-28 07:37 UTC
